{% set name = "deepmerge" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/deepmerge-{{ version }}.tar.gz
  sha256: f6fd7f1293c535fb599e197e750dbe8674503c5d2a89759b3c72a3c46746d4fd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools-scm
  run:
    - python >=3.5

test:
  imports:
    - deepmerge
    - deepmerge.strategy
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://deepmerge.readthedocs.io/en/latest/
  summary: a toolset to deeply merge python dictionaries.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
